/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IChatGpt__factory } from "./IChatGpt__factory";
export { IOracle__factory } from "./IOracle__factory";
