/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOracle,
  IOracleInterface,
} from "../../../contracts/interfaces/IOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "functionCallbackId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "functionType",
        type: "string",
      },
      {
        internalType: "string",
        name: "functionInput",
        type: "string",
      },
    ],
    name: "createFunctionCall",
    outputs: [
      {
        internalType: "uint256",
        name: "i",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "promptId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "string",
            name: "model",
            type: "string",
          },
          {
            internalType: "int8",
            name: "frequencyPenalty",
            type: "int8",
          },
          {
            internalType: "string",
            name: "logitBias",
            type: "string",
          },
          {
            internalType: "uint32",
            name: "maxTokens",
            type: "uint32",
          },
          {
            internalType: "int8",
            name: "presencePenalty",
            type: "int8",
          },
          {
            internalType: "string",
            name: "responseFormat",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "seed",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "stop",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "temperature",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "topP",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "user",
            type: "string",
          },
        ],
        internalType: "struct IOracle.GroqRequest",
        name: "request",
        type: "tuple",
      },
    ],
    name: "createGroqLlmCall",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "kbQueryCallbackId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "cid",
        type: "string",
      },
      {
        internalType: "string",
        name: "query",
        type: "string",
      },
      {
        internalType: "uint32",
        name: "num_documents",
        type: "uint32",
      },
    ],
    name: "createKnowledgeBaseQuery",
    outputs: [
      {
        internalType: "uint256",
        name: "i",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "promptId",
        type: "uint256",
      },
    ],
    name: "createLlmCall",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "promptId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "string",
            name: "model",
            type: "string",
          },
          {
            internalType: "int8",
            name: "frequencyPenalty",
            type: "int8",
          },
          {
            internalType: "string",
            name: "logitBias",
            type: "string",
          },
          {
            internalType: "uint32",
            name: "maxTokens",
            type: "uint32",
          },
          {
            internalType: "int8",
            name: "presencePenalty",
            type: "int8",
          },
          {
            internalType: "string",
            name: "responseFormat",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "seed",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "stop",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "temperature",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "topP",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "tools",
            type: "string",
          },
          {
            internalType: "string",
            name: "toolChoice",
            type: "string",
          },
          {
            internalType: "string",
            name: "user",
            type: "string",
          },
        ],
        internalType: "struct IOracle.OpenAiRequest",
        name: "request",
        type: "tuple",
      },
    ],
    name: "createOpenAiLlmCall",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IOracleInterface {
    return new Interface(_abi) as IOracleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IOracle {
    return new Contract(address, _abi, runner) as unknown as IOracle;
  }
}
