/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { AIProposalAdvisor } from "./AIProposalAdvisor";
export type { Agent } from "./Agent";
export type { ChatGpt } from "./ChatGpt";
export type { ChatOracle } from "./ChatOracle";
export type { DalleNft } from "./DalleNft";
export type { GroqChatGpt } from "./GroqChatGpt";
export type { OpenAiChatGpt } from "./OpenAiChatGpt";
export type { OpenAiChatGptVision } from "./OpenAiChatGptVision";
export type { Quickstart } from "./Quickstart";
export type { Test } from "./Test";
export type { Vitailik } from "./Vitailik";
