/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IOracle {
  export type ContentStruct = { contentType: string; value: string };

  export type ContentStructOutput = [contentType: string, value: string] & {
    contentType: string;
    value: string;
  };

  export type MessageStruct = {
    role: string;
    content: IOracle.ContentStruct[];
  };

  export type MessageStructOutput = [
    role: string,
    content: IOracle.ContentStructOutput[]
  ] & { role: string; content: IOracle.ContentStructOutput[] };

  export type GroqResponseStruct = {
    id: string;
    content: string;
    created: BigNumberish;
    model: string;
    systemFingerprint: string;
    object: string;
    completionTokens: BigNumberish;
    promptTokens: BigNumberish;
    totalTokens: BigNumberish;
  };

  export type GroqResponseStructOutput = [
    id: string,
    content: string,
    created: bigint,
    model: string,
    systemFingerprint: string,
    object: string,
    completionTokens: bigint,
    promptTokens: bigint,
    totalTokens: bigint
  ] & {
    id: string;
    content: string;
    created: bigint;
    model: string;
    systemFingerprint: string;
    object: string;
    completionTokens: bigint;
    promptTokens: bigint;
    totalTokens: bigint;
  };

  export type OpenAiResponseStruct = {
    id: string;
    content: string;
    functionName: string;
    functionArguments: string;
    created: BigNumberish;
    model: string;
    systemFingerprint: string;
    object: string;
    completionTokens: BigNumberish;
    promptTokens: BigNumberish;
    totalTokens: BigNumberish;
  };

  export type OpenAiResponseStructOutput = [
    id: string,
    content: string,
    functionName: string,
    functionArguments: string,
    created: bigint,
    model: string,
    systemFingerprint: string,
    object: string,
    completionTokens: bigint,
    promptTokens: bigint,
    totalTokens: bigint
  ] & {
    id: string;
    content: string;
    functionName: string;
    functionArguments: string;
    created: bigint;
    model: string;
    systemFingerprint: string;
    object: string;
    completionTokens: bigint;
    promptTokens: bigint;
    totalTokens: bigint;
  };
}

export interface TestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "callFunction"
      | "callGroqLLM"
      | "callOpenAiLLM"
      | "callOpenAiVisionLLM"
      | "getMessageHistory"
      | "getMessageHistoryContents"
      | "getMessageHistoryRoles"
      | "lastError"
      | "lastResponse"
      | "llmMessage"
      | "onOracleFunctionResponse"
      | "onOracleGroqLlmResponse"
      | "onOracleKnowledgeBaseQueryResponse"
      | "onOracleOpenAiLlmResponse"
      | "oracleAddress"
      | "queryKnowledgeBase"
      | "setOracleAddress"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OracleAddressUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "callFunction",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "callGroqLLM",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "callOpenAiLLM",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "callOpenAiVisionLLM",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageHistoryContents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageHistoryRoles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "lastError", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastResponse",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "llmMessage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onOracleFunctionResponse",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "onOracleGroqLlmResponse",
    values: [BigNumberish, IOracle.GroqResponseStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "onOracleKnowledgeBaseQueryResponse",
    values: [BigNumberish, string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "onOracleOpenAiLlmResponse",
    values: [BigNumberish, IOracle.OpenAiResponseStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "queryKnowledgeBase",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracleAddress",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "callFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callGroqLLM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callOpenAiLLM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callOpenAiVisionLLM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageHistoryContents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageHistoryRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastError", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "llmMessage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onOracleFunctionResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onOracleGroqLlmResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onOracleKnowledgeBaseQueryResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onOracleOpenAiLlmResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryKnowledgeBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOracleAddress",
    data: BytesLike
  ): Result;
}

export namespace OracleAddressUpdatedEvent {
  export type InputTuple = [newOracleAddress: AddressLike];
  export type OutputTuple = [newOracleAddress: string];
  export interface OutputObject {
    newOracleAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Test extends BaseContract {
  connect(runner?: ContractRunner | null): Test;
  waitForDeployment(): Promise<this>;

  interface: TestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  callFunction: TypedContractMethod<
    [name: string, message: string],
    [bigint],
    "nonpayable"
  >;

  callGroqLLM: TypedContractMethod<
    [model: string, message: string],
    [bigint],
    "nonpayable"
  >;

  callOpenAiLLM: TypedContractMethod<
    [model: string, message: string],
    [bigint],
    "nonpayable"
  >;

  callOpenAiVisionLLM: TypedContractMethod<
    [model: string, message: string, imageUrl: string],
    [bigint],
    "nonpayable"
  >;

  getMessageHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [IOracle.MessageStructOutput[]],
    "view"
  >;

  getMessageHistoryContents: TypedContractMethod<
    [arg0: BigNumberish],
    [string[]],
    "view"
  >;

  getMessageHistoryRoles: TypedContractMethod<
    [arg0: BigNumberish],
    [string[]],
    "view"
  >;

  lastError: TypedContractMethod<[], [string], "view">;

  lastResponse: TypedContractMethod<[], [string], "view">;

  llmMessage: TypedContractMethod<[], [string], "view">;

  onOracleFunctionResponse: TypedContractMethod<
    [arg0: BigNumberish, response: string, errorMessage: string],
    [void],
    "nonpayable"
  >;

  onOracleGroqLlmResponse: TypedContractMethod<
    [
      arg0: BigNumberish,
      response: IOracle.GroqResponseStruct,
      errorMessage: string
    ],
    [void],
    "nonpayable"
  >;

  onOracleKnowledgeBaseQueryResponse: TypedContractMethod<
    [arg0: BigNumberish, documents: string[], errorMessage: string],
    [void],
    "nonpayable"
  >;

  onOracleOpenAiLlmResponse: TypedContractMethod<
    [
      arg0: BigNumberish,
      response: IOracle.OpenAiResponseStruct,
      errorMessage: string
    ],
    [void],
    "nonpayable"
  >;

  oracleAddress: TypedContractMethod<[], [string], "view">;

  queryKnowledgeBase: TypedContractMethod<
    [cid: string, query: string],
    [bigint],
    "nonpayable"
  >;

  setOracleAddress: TypedContractMethod<
    [newOracleAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "callFunction"
  ): TypedContractMethod<
    [name: string, message: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callGroqLLM"
  ): TypedContractMethod<
    [model: string, message: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callOpenAiLLM"
  ): TypedContractMethod<
    [model: string, message: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callOpenAiVisionLLM"
  ): TypedContractMethod<
    [model: string, message: string, imageUrl: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMessageHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [IOracle.MessageStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMessageHistoryContents"
  ): TypedContractMethod<[arg0: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMessageHistoryRoles"
  ): TypedContractMethod<[arg0: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "lastError"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastResponse"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "llmMessage"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onOracleFunctionResponse"
  ): TypedContractMethod<
    [arg0: BigNumberish, response: string, errorMessage: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onOracleGroqLlmResponse"
  ): TypedContractMethod<
    [
      arg0: BigNumberish,
      response: IOracle.GroqResponseStruct,
      errorMessage: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onOracleKnowledgeBaseQueryResponse"
  ): TypedContractMethod<
    [arg0: BigNumberish, documents: string[], errorMessage: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onOracleOpenAiLlmResponse"
  ): TypedContractMethod<
    [
      arg0: BigNumberish,
      response: IOracle.OpenAiResponseStruct,
      errorMessage: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "oracleAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "queryKnowledgeBase"
  ): TypedContractMethod<[cid: string, query: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "setOracleAddress"
  ): TypedContractMethod<[newOracleAddress: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OracleAddressUpdated"
  ): TypedContractEvent<
    OracleAddressUpdatedEvent.InputTuple,
    OracleAddressUpdatedEvent.OutputTuple,
    OracleAddressUpdatedEvent.OutputObject
  >;

  filters: {
    "OracleAddressUpdated(address)": TypedContractEvent<
      OracleAddressUpdatedEvent.InputTuple,
      OracleAddressUpdatedEvent.OutputTuple,
      OracleAddressUpdatedEvent.OutputObject
    >;
    OracleAddressUpdated: TypedContractEvent<
      OracleAddressUpdatedEvent.InputTuple,
      OracleAddressUpdatedEvent.OutputTuple,
      OracleAddressUpdatedEvent.OutputObject
    >;
  };
}
